### PR TITLE
Adds back support to page.pdf()

### PR DESCRIPTION
**Pull request by celso**
Adds back support to page.pdf() using Cloudflare Workers Streams and Buffers support.

### CODE REVIEW

**Review by philsyme — APPROVED** [review]

**Review by edevil — APPROVED** [review]

**Comment by sokki** [comment]
Since this change, I'm not able to build/deploy any of the examples. Downgrading to `0.0.1` or `0.0.2-alpha` fixes the issue.
image

**Comment by celso** [comment]
@sokki can you please add this to your wrangler.toml configuration file and see if it solves the issue?

`compatibility_flags = [ "nodejs_compat" ]`

**Comment by sokki** [comment]
@celso switching from `node_compat = true` to `compatibility_flags = [ "nodejs_compat" ]` changes the error messages:
image

I'm using the latest wrangler `3.3.0`

**Comment by denu5** [comment]
`compatibility_flags = [ "nodejs_compat" ]` as suggested by @celso fixed the issue for me

**Comment by AlwaysAwake** [comment]
I've tried `compatibility_flags = [ "nodejs_compat" ]`, 
but it keep saying
```json
{"name":"TypeError","message":"Cannot read properties of undefined (reading 'fetch')","stack":"TypeError: Cannot read properties of undefined (reading 'fetch')\n    at PuppeteerWorkers.launch (worker.js:10201:32)\n    at requestCooling (worker.js:10227:48)\n    at worker.js:10328:9\n    at async Object.handle (worker.js:548:29)\n    at async jsonError (worker.js:10356:12)"}
```

**Comment by celso** [comment]
Can you paste your code and wrangler.toml?

**Comment by fynntang** [comment]
Hi @celso , I also encountered the same problem

> Cannot read properties of undefined (reading 'fetch')

**wrangler.toml**
```
name = "pupp"
account_id = "**********"
main = "src/worker.ts"
compatibility_date = "2023-08-07"
compatibility_flags = ["nodejs_compat"]
workers_dev = true

[placement]
mode = "smart"

browser = { binding = "BROWSER", type = "browser" }

[[kv_namespaces]]
binding = "BROWSER_KV"
id = "**********"
preview_id = "**********"

```

**worker-configuration.d.ts**
```
interface Env {
	BROWSER_KV: KVNamespace;
	BROWSER: Fetcher;
}

```

**src/worker.ts**
```
import puppeteer from '@cloudflare/puppeteer';
export default {
	async fetch(request: Request, env: Env, ctx: ExecutionContext): Promise<Response> {
		const { searchParams } = new URL(request.url);
		let url = searchParams.get('url');

		if (!url) { return new Response('Not allowed', { status: 401 });}

		url = new URL(url).toString();
		let content: string | null = null;
		// content = await env.BROWSER_KV.get(url, { type: 'text' });

		if (content === null) {
			const browser = await puppeteer.launch(env.BROWSER);
			const page = await browser.newPage();
			await page.goto(url);
			content = await page.content();

			// await env.BROWSER_KV.put(url, content, { expirationTtl: 60 * 60 * 24 });
			await browser.close();
		}

		return new Response(content, { headers: { 'Content-Type': 'text/html; charset=utf-8' } });
	}
};
```



**logs**
```
{
  "outcome": "exception",
  "scriptName": "pupp",
  "diagnosticsChannelEvents": [],
  "exceptions": [
    {
      "name": "TypeError",
      "message": "Cannot read properties of undefined (reading 'fetch')",
      "timestamp": 1691756919302
    }
  ],
  "logs": [],
  "eventTimestamp": 1691756919302,
  "event": {
    "request": {
      "url": "https://pupp.fzpying.workers.dev/?url=http://huxi.io",
      "method": "GET",
      "headers": {
        "accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7",
        "accept-encoding": "gzip",
        "accept-language": "zh-CN,zh;q=0.9",
        "cache-control": "no-cache",
        "cf-connecting-ip": "***.***.***.***",
        "cf-ipcountry": "JP",
        "cf-ray": "7f507ac99bc0f57b",
        "cf-visitor": "{\"scheme\":\"https\"}",
        "connection": "Keep-Alive",
        "host": "pupp.fzpying.workers.dev",
        "pragma": "no-cache",
        "sec-ch-ua": "\"Not/A)Brand\";v=\"99\", \"Google Chrome\";v=\"115\", \"Chromium\";v=\"115\"",
        "sec-ch-ua-mobile": "?0",
        "sec-ch-ua-platform": "\"macOS\"",
        "sec-fetch-dest": "document",
        "sec-fetch-mode": "navigate",
        "sec-fetch-site": "none",
        "sec-fetch-user": "?1",
        "upgrade-insecure-requests": "1",
        "user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36",
        "x-forwarded-proto": "https",
        "x-real-ip": "***.***.***.***"
      },
      "cf": {
        "clientTcpRtt": 1,
        "longitude": "139.68990",
        "latitude": "35.68930",
        "tlsCipher": "AEAD-AES128-GCM-SHA256",
        "continent": "AS",
        "asn": 63949,
        "clientAcceptEncoding": "gzip, deflate, br",
        "country": "JP",
        "tlsClientAuth": {
          "certIssuerDNLegacy": "",
          "certIssuerSKI": "",
          "certSubjectDNRFC2253": "",
          "certSubjectDNLegacy": "",
          "certFingerprintSHA256": "",
          "certNotBefore": "",
          "certSKI": "",
          "certSerial": "",
          "certIssuerDN": "",
          "certVerified": "NONE",
          "certNotAfter": "",
          "certSubjectDN": "",
          "certPresented": "0",
          "certRevoked": "0",
          "certIssuerSerial": "",
          "certIssuerDNRFC2253": "",
          "certFingerprintSHA1": ""
        },
        "tlsExportedAuthenticator": {
          "clientFinished": "**********",
          "clientHandshake": "**********",
          "serverHandshake": "**********",
          "serverFinished": "**********"
        },
        "tlsVersion": "TLSv1.3",
        "colo": "NRT",
        "timezone": "Asia/Tokyo",
        "city": "Tokyo",
        "edgeRequestKeepAliveStatus": 1,
        "requestPriority": "weight=256;exclusive=1",
        "httpProtocol": "HTTP/2",
        "region": "Tokyo",
        "regionCode": "13",
        "asOrganization": "Akamai Connected Cloud",
        "postalCode": "151-0053",
        "botManagement": {
          "corporateProxy": false,
          "verifiedBot": false,
          "jsDetection": {
            "passed": false
          },
          "staticResource": false,
          "detectionIds": {},
          "score": 99
        }
      }
    },
    "response": {
      "status": 500
    }
  },
  "id": 10
}
```

**Comment by meddulla** [comment]
@fynntang Can you move the browser section (`browser = { binding = "BROWSER", type = "browser" }`) to before the `[..]` keys and try again::

```

browser = { binding = "BROWSER", type = "browser" }

[placement]
mode = "smart"

[[kv_namespaces]]
binding = "BROWSER_KV"
id = "**********"
preview_id = "**********"

```

**Comment by fynntang** [comment]
> @fynntang Can you move the browser binding (ie. `browser = { binding = "BROWSER", type = "browser" }`) to before the `[..]` keys in `wrangler.toml` and try again:
> 
> ```
> 
> browser = { binding = "BROWSER", type = "browser" }
> 
> [placement]
> mode = "smart"
> 
> [[kv_namespaces]]
> binding = "BROWSER_KV"
> id = "**********"
> preview_id = "**********"
> ```

hi @meddulla , Your method can run smoothly, thanks

At the same time, I also found that the following method can be used for binding

```
[[unsafe.bindings]]
name = "MYBROWSER"
binding = "MYBROWSER"
type = "browser"
```

**Pull request merged**
